version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - run: apt-get install -y git ssh 
      - checkout
      - run: apt-get install -y g++
      - run: g++ helloworld.cpp -o helloworld
      - run: ./helloworld
